### ISSUE TITLE
9.2.0-11289 - Restart does not work 

### ISSUE THREAD

**Issue by TLHD** [ohyeah521/Surveillance-Station#1]
1. SS is working as it is supposed to within DSM and with Apps
2. Licenses are working as supposed
3. Hostfile is edited
4. But it stops working after about an hour , no more App Connections possible, and started from DSM it greys out
5. I helped me out by creating 2 Tasks. One stopping the service every hour. And the other one starting it again 2mins later.

**Comment by ohyeah521** [comment]
I reproduced this scene, it should be the time bomb added in the new version

**Comment by TLHD** [comment]
Didn't the previous one have one as well?
and would it be possible to do an "automatic" restart like in the previous one?

**Comment by ohyeah521** [comment]
I'm a little busy at the end of the month, I'll crack it again next month to get around this restriction

**Comment by roumegaire** [comment]
Hello same pb here on DS918+

TLHD could you send the script for the 2 tasks please ? I'm afraid not to be smart enough ...

Thanks !

**Comment by MKatsay** [comment]
Hi, I tested it again, now the result is the following: every hour the service just stops and starts again. Unfortunately, this is not convenient for monitoring. but in general, the license works and helps. But for those who are critical, continuous recording or recording is very important - they will lose 10 seconds every hour.

**Comment by ohyeah521** [comment]
@MKatsay  I have solved the time bomb problem. It has been completely cracked and there is no problem of automatic stopping after 1 hour. I need you to provide your software architecture information and the following 2 files:

```
/var/packages/SurveillanceStation/target/lib/libssutils.so
/var/packages/SurveillanceStation/target/sbin/sscored
```

**Comment by TLHD** [comment]
> @MKatsay  I have solved the time bomb problem. It has been completely cracked and there is no problem of automatic stopping after 1 hour. I need you to provide your software architecture information and the following 2 files:
> 
> ```
> /var/packages/SurveillanceStation/target/lib/libssutils.so
> /var/packages/SurveillanceStation/target/sbin/sscored
> ```

General fix? Or plattform specific? (still have the same problem)

**Comment by ohyeah521** [comment]
@TLHD  for all platform

**Comment by ohyeah521** [comment]
@Moll355 A new cracked version will be released soon

**Comment by Moll355** [comment]
Will version 9.1.2 work better than version 9.2.0?
I need to install it today, but I'm in a hurry.

**Comment by ohyeah521** [comment]
@Moll355  no, install 9.2.0, wait my patch

**Comment by Moll355** [comment]
All right. I hope it happens soon

**Comment by ohyeah521** [comment]
@Moll355 I'm doing the final tests, and if nothing unexpected happens, I should be able to release a patch for the Intel architecture today.

**Comment by Moll355** [comment]
Wow Oh I really hope so. thank you for your hard work.
But will there be any problem if I use it on a genuine Synology?

**Comment by ohyeah521** [comment]
no, i had patch license check

**Comment by Moll355** [comment]
It's really nice. Thank you.

**Comment by ohyeah521** [comment]
@Moll355  SurveillanceStation-x86_64  release!

`bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/SurveillanceStation-x86_64/install_license)`

**Comment by Moll355** [comment]
Wow very thank you I will test today
