### ISSUE TITLE
Cameras disappear after a day

### ISSUE THREAD

**Issue by Alikerks** [ohyeah521/Surveillance-Station#2]
Hello,

Thank you for you work, much appreciated.

I would like to bring to you a issue i'm facing after about a day, all cameras disappeared from the camera list and i must restart ss service to get my cameras back. When the cameras are gone, i can still connect to dscam but no camera, detection are notifying for no reason.

I configured a task to restart ss once a day but seems not enough because i'm still experiencing the issue. I configured a restart every 4 hours.

Do you have any clue why

**Comment by ohyeah521** [comment]
first:
`bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/license/remove_license)`

sencond:
`bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/SurveillanceStation-x86_64/install_license)`


third:
wait and see!

**Comment by Alikerks** [comment]
Hello,

Thank you for your help. i'm going to test it.

**Comment by Moll355** [comment]
I've been testing it since I installed it, and it continues to record and works very well.

**Comment by Moll355** [comment]
It stopped again. Is there any way to fix it?

**Comment by Moll355** [comment]
It stopped again. Can you help me solve it?

**Comment by ohyeah521** [comment]
@Moll355 Completely uninstalled ss, then reinstalled, applied my patch

**Comment by Alikerks** [comment]
Mine is still ok since yesterday
