### ISSUE TITLE
After Reboot Surveillance Station is Inactive

### ISSUE THREAD

**Issue by qwe33gthb** [ohyeah521/Surveillance-Station#2]
Surveillance Station application is inaccessible every time I start it. I have to run the code every time. I think it has to do with setting the hosts file. However, I could not set the hosts file and I could not find any information on how to do it. If someone who knows can help me, I would be glad.

**Comment by ohyeah521** [comment]
echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc/hosts

**Comment by qwe33gthb** [comment]
with putty and ssh? Thank you for reply

**Comment by qwe33gthb** [comment]
I guess it doesn't work. Every time I start the system it gives the following error: 
Sorry, the page you were looking for was not found.

![resim](https://github.com/user-attachments/assets/96b39519-92d8-4c08-a219-f85db6831afe)
