### ISSUE TITLE
 vi /etc/hosts

### ISSUE THREAD

**Issue by javifly** [ohyeah521/Surveillance-Station#3]
it is possible to run 

vi /etc/hosts
and
0.0.0.0.0 synosurveillance.synology.com

in one command? something like this?

vi /etc/hosts add 0.0.0.0.0 synosurveillance.synology.com

**Comment by ohyeah521** [comment]
user this command 

`echo "0.0.0.0 synosurveillance.synology.com" | sudo tee -a /etc/hosts`

**Comment by javifly** [comment]
perfect! If it works well, don't you think it would be easier to execute and it would be advisable to put it in the guide?

another doubt, this command could be executed from a script of the scheduled tasks tool in the same way as the other command is executed?

**Comment by AmmokPT** [comment]
how to edit hosts?

**Comment by javifly** [comment]
You have to edit the host-file, otherwise it will reboot after one hour and loose the licenses...

You can either edit the hosts-file with vi or nano from the SSH-terminal or you can log into shell via ssh and execute the line that is described here under "block license check": https://github.com/ohyeah521/Surveillance-Station

Hope this helps.

**Comment by javifly** [comment]
another doubt, this command could be executed from a script of the scheduled tasks tool in the same way as the other command is executed?

I don't know if running it in the same script or in a separate one... is it possible?

**Comment by ohyeah521** [comment]
@javifly  added:
[https://github.com/ohyeah521/Surveillance-Station/blob/main/9.2.0_11289/SurveillanceStation-x86_64/install_license]( https://github.com/ohyeah521/Surveillance-Station/blob/main/9.2.0_11289/SurveillanceStation-x86_64/install_license)

**Comment by javifly** [comment]
ok, so in your initial manual https://github.com/ohyeah521/Surveillance-Station/tree/main

is this left over, “0.0.0.0.0 synosurveillance.synology.com” |udo tee -a /etc/hosts ??? 

if running the script does everything, we don't need to edit the host file by hand, do we?

**Comment by ohyeah521** [comment]
yes

**Comment by javifly** [comment]
Do you plan to remove it from the guide?

**Comment by vadimon8** [comment]
@ohyeah521 Hello! I did everything as described. Connected via SHH, changed host, but it still crashes every hour

**Comment by ohyeah521** [comment]
@javifly @vadimon8  @AmmokPT     The latest patch has been released, currently only supports x86-64 platform, you need to uninstall ss, reinstall ss, and finally apply my patch
