### ISSUE TITLE
Sorry the page you are looking for is not found

### ISSUE THREAD

**Issue by raenrfm** [ohyeah521/Surveillance-Station#4]
After running the script the  SS app shuts down and doesn't come back.  What am I missing here?  Is the download link optional or does it have to be put back on the NAS after the script is run?  

How long does the script take to run also will this work on my 218j?

**Comment by ohyeah521** [comment]
First, please confirm that your Synology is an x86 architecture. Secondly, please make sure that your Synology can connect to github. If the operation through the web page fails, you can change to SSH to log in, and then paste the installation command. It usually takes about 2 minutes. It depends on the details. your internet speed

**Comment by raenrfm** [comment]
Ah I think the chipset is the problem then....its Marvell Armada 385 88F6820.  So this won't work at all and I will have to buy the licenses?

**Comment by ohyeah521** [comment]
If you know some linux commands, you can try to extract the following file and send it to me. I will try it.

` /var/packages/SurveillanceStation/target/lib/libssutils.so`

**Comment by raenrfm** [comment]
How do you extract an .so file?

**Comment by ohyeah521** [comment]
1、install from store
2、login with ssh
3、sudo cp /var/packages/SurveillanceStation/target/lib/libssutils.so     /volume1/{your share folder name}

**Comment by raenrfm** [comment]
Oh you said extract so I thought you wanted me to do something to the file itself.  I'll send it to you shortly.

**Comment by raenrfm** [comment]
Here is the file.
[libssutils.zip](https://github.com/user-attachments/files/16443237/libssutils.zip)

**Comment by ohyeah521** [comment]
@raenrfm  try:
`bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/SurveillanceStation-Armada/install_license)`

**Comment by raenrfm** [comment]
That worked!!

**Comment by ohyeah521** [comment]
bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/license/remove_license)

**Comment by raenrfm** [comment]
So one thing that is happening now is that I have to restart the service in order to get it to work as when I load up the SS web interface it's loaded but the page it blank.  A restart gets it going again.

**Comment by domi1968** [comment]
hello ,Me too
SS is working as it is supposed to within DSM and with Apps
Licenses are working as supposed
Hostfile is edited
But it stops working after about an hour , no more App Connections possible, and started from DSM it greys out
help my

**Comment by raenrfm** [comment]
Mine seems to run fine for the day but then after midnight (not sure if some job that runs is causing this) it stops working.  I suppose I could just set up a task to stop and start the service after midnight, but that's not ideal.

**Comment by ohyeah521** [comment]
I have updated the program. You need to uninstall it according to the instructions in the readme. Waiting for the uninstallation to complete and then reinstalling should solve the problem.

**Comment by Alikerks** [comment]
Could someone confirm that everything is fine now ?

**Comment by domi1968** [comment]
no But it stops working after about an hour ,Link download forMarvell Armada (9.2.0-11289) sory in french good job

**Comment by raenrfm** [comment]
My Nas is now acting up. Cannot get the web login now. Need to reboot the Nas to bring it back which isn't good.  Has anyone else had this problem?

**Comment by raenrfm** [comment]
My nas is super slow today having trouble logging into it now.  I think something is wrong with this whole thing.  Am I being hacked here?

**Comment by Alikerks** [comment]
stick to the hack on version 9.1.2, it is stable.

**Comment by raenrfm** [comment]
I figured out what was going on.  I didn't delete the task so I think it just kept running.  It would be good to mention why you need to delete the task after running it because even though it's not "enabled" I think it just continues to run once you manually start it.  I thought it would just exit after completing but that's not the case it seems.

**Comment by raenrfm** [comment]
New problem....NAS seems to have settled down now but now my cameras all go to "stopping" and sit there after a while, not sure how long.  I then have to disable them then re-enable them to bring them back.

**Comment by ohyeah521** [comment]
@raenrfm 
This is a time bomb. Please follow the instructions in the readme to remove first, and then execute the install command again. I have already updated the program.

**Comment by raenrfm** [comment]
The trick was a complete uninstall including the existing licenses and then starting from scratch.  All good now.

**Comment by raenrfm** [comment]
Ok so is it normal that I will see the camera become unavailable and then idle every hour?

![image](https://github.com/user-attachments/assets/7eb9c944-5ac3-464b-9062-4f3117540333)

**Comment by raenrfm** [comment]
Can you explain the uninstall process?  You don't explain it in the readme, so I'm not sure what you're talking about other than running the license remove script and then re-installing SS?

**Comment by ohyeah521** [comment]
use putty to login you dsm, then run this:
`bash <(curl -L https://raw.githubusercontent.com/ohyeah521/Surveillance-Station/main/9.2.0_11289/license/remove_license)`

**Comment by domi1968** [comment]
there is always a loss of connection all the 
![Capture d’écran 2024-08-10 133112](https://github.com/user-attachments/assets/810ff490-44ab-43d2-9076-030a1e21a8b9)
time

**Comment by ohyeah521** [comment]
@raenrfm  I need another file to achieve full crack
file path: /var/packages/SurveillanceStation/target/sbin/sscored
