### ISSUE TITLE
无法预览 H265/264 视频摄像头

### ISSUE THREAD

**Issue by dingdayu** [ohyeah521/Surveillance-Station#5]
在 DSM  7.2.2 上 通过修改 synopackageslimit.conf 方式安装了 Surveillance-Station 9.2.0-11289，AME 30.1.0-3005，补充安装了 MediaServer 2.1.0-3304。

记录与： https://gist.github.com/dingdayu/c5f36d007249249ca7afba93c102359b

安装后，能过正常使用，正常录制，通过 文件夹管理查看过视频录像文件，可以查看到视频是正常的，但是无法在 Surveillance-Station 预览，如下图中如论设置相机编码 为 H264 还是设置为 H265，AME 编码入下截图所示。

请教如何能够在 Surveillance-Station 中直接 预览，另附 在客户端中也是如此提示，另，每次尝试都有重启，到目前为止都无效。

## 版本

![CleanShot 2024-10-05 at 13 52 41@2x](https://github.com/user-attachments/assets/58320306-abcc-49eb-844c-5ec8ae94c774)

![CleanShot 2024-10-05 at 13 54 32@2x](https://github.com/user-attachments/assets/819857e7-c506-409d-9d74-77169acb4210)

## 相关截图
![CleanShot 2024-10-05 at 13 48 39@2x](https://github.com/user-attachments/assets/e879cf1a-5624-461e-a446-2b144772fbac)
![CleanShot 2024-10-05 at 13 49 31@2x](https://github.com/user-attachments/assets/99f3af1e-0254-4b8e-9c53-94ae40edb039)
![CleanShot 2024-10-05 at 13 49 48@2x](https://github.com/user-attachments/assets/639f7f56-d9a5-4cfd-aae5-75fcb72dcbbe)
![CleanShot 2024-10-05 at 13 50 17@2x](https://github.com/user-attachments/assets/3cc97ef4-c0fa-4cc2-9c3f-1f60d263385b)
![CleanShot 2024-10-05 at 13 51 34@2x](https://github.com/user-attachments/assets/4b0a612f-e8e0-4a16-a15b-6d56321711df)
![CleanShot 2024-10-05 at 13 51 47@2x](https://github.com/user-attachments/assets/e7752e40-5c3b-40c6-aafc-f183a47e088a)

**Comment by ohyeah521** [comment]
不建议这么搞，群晖为了实现存算分离，把解码功能给阉割了，不知道他们系统底层都删了哪些代码。成本太高

**Comment by dingdayu** [comment]
大佬都这样说，真的不能在 7.2.2 上使用 Surveillance-Station 吗 🤦

**Comment by ohyeah521** [comment]
要使用它对应的版本，它的发布说明里面解释了，7.2.2必须要使用最新的ss

**Comment by dingdayu** [comment]
好的，我打算再最后尝试 安装 FFMPEG 然后不从就回退回 7.2.1 。
