### ISSUE TITLE
请检查一下，好像隔一段时间surveillance就停止服务了。

### ISSUE THREAD

**Issue by thirty** [ohyeah521/Surveillance-Station#5]
必须手动停止以后才可以用。
目前还在观察这种现象出现的机率

**Comment by thirty** [comment]
又出现了。 大概2小时左右出现一次

**Comment by ohyeah521** [comment]
应该是加入了暗桩，在某个位置再次检测注册信息了

**Comment by ohyeah521** [comment]
先执行一下卸载命令，然后在重新安装，应该可以解决停止服务的问题，我测试了几次好像可以了

**Comment by WayChan** [comment]
> 先执行一下卸载命令，然后在重新安装，应该可以解决停止服务的问题，我测试了几次好像可以了

重启ssctl的时候实际上也会让服务重启，导致录制一段一段的

**Comment by ohyeah521** [comment]
是的，目前只能这样，它这个程序有几十个库相互调用，特别恶心，不知道把时间炸弹藏在哪里了

**Comment by ohyeah521** [comment]
新的补丁发布了，已经去除了时间炸弹。需要卸载ss，然后重新安装，最后在应用最新的补丁即可
