### ISSUE TITLE
有严重bug，路由器崩溃

### ISSUE THREAD

**Issue by fay000fay** [ohyeah521/Surveillance-Station#7]
我主路由是硬路由刷的Immortalwrt，软路由里安装的黑群晖，然后在黑群晖里安装了作者这个版本后，没几分钟，主路由的延迟就会非常高，然后直接无法联网。停掉这个组件后，一切正常。然后我卸载该版本，安装了9.1.2的破解版后，一切正常。不知道是不是个例

**Comment by ohyeah521** [comment]
这个问题你应该去找群晖反馈
