### ISSUE TITLE
"9.2.1-11380"

### ISSUE THREAD

**Issue by onedayblack** [ohyeah521/Surveillance-Station#8]
Hello,

Currently, the latest version is 9.2.1-11380. Will you be providing compatibility for this version?

thank you

**Comment by saschape** [comment]
Hello,

i would also be interested in version 9.2.1-11380.

thank you

**Comment by ohyeah521** [comment]
I guess I’ll have to wait until next year, I’m a bit busy at the end of the year

**Comment by AmmokPT** [comment]
so many time to wait :(
can you please make it before that?

**Comment by AmmokPT** [comment]
hi @ohyeah521 , any news?

**Comment by mowdep** [comment]
to anyone who ended here after upgrade your DSM to latest version and can't anymore install the version 9.2.0-11289 : 

SSH into your DSM then run (as sudo -i or root) 
`
```shell
cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
```

And now you can install from GUI the [9.2.0-11289 ](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289)

And if you want to prevent upgrade displaying in package center, just run these line (as sudo -i or root) in the cli : 

```shell
cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
 ```

(edit : formatting)

**Comment by AmmokPT** [comment]
@ohyeah521 can you use that has a fix?

**Comment by ohyeah521** [comment]
> @ohyeah521 can you use that has a fix?

I won't do that, because I don't recommend upgrading to dsm 7.2.2. Many functions have been castrated, and the risks of doing so are unknown. You need to do it yourself so that you understand all the risks. I don’t want anyone who doesn’t understand to run these commands, because incorrect operation may cause data loss. After all, the first priority of NAS is to ensure data security.

**Comment by AmmokPT** [comment]
I agree with you. well, for me is just a pain in the azz because all my cameras are "down" :(

**Comment by mowdep** [comment]
@ohyeah521 , I'm curious, have you a list of functions that have been truncated ? 
I don't see any risk in modify synopackageslimit.conf and package/INFO but I can completely miss the point (other than the OS corruption inherent with running random script from internet :) )

**Comment by helio58** [comment]
> to anyone who ended here after upgrade your DSM to latest version and can't anymore install the version 9.2.0-11289 :
> 
> SSH into your DSM then run (as sudo -i or root) `
> 
> ```shell
> cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
> sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
> ```
> 
> And now you can install from GUI the [9.2.0-11289 ](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289)
> 
> And if you want to prevent upgrade displaying in package center, just run these line (as sudo -i or root) in the cli :
> 
> ```shell
> cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
> sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
> ```
> 
> (edit : formatting)

Tried but unable to install  9.2.0-11289

**Comment by caspercze** [comment]
> > komukoli, kdo zde skončil po upgradu vašeho DSM na nejnovější verzi a nemůže již nainstalovat verzi 9.2.0-11289:
> > SSH do vašeho DSM a poté spusťte (jako sudo -i nebo root) `
> > ```shell
> > cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
> > sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A nyní můžete nainstalovat z GUI [9.2.0-11289](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289)
> > A pokud chcete zabránit zobrazování upgradu v centru balíčků, stačí spustit tento řádek (jako sudo -i nebo root) v cli :
> > ```shell
> > cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
> > sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (upravit: formátování)
> 
> Vyzkoušeno, ale nelze nainstalovat 9.2.0-11289

It works for me, properly installed version 9.2.0-11289 and license active.

DS224+ / DSM 7.2.2-72806 Update 2

**Comment by Hsarmien1016** [comment]
> > > komukoli, kdo zde skončil po upgradu vašeho DSM na nejnovější verzi a nemůže již nainstalovat verzi 9.2.0-11289:
> > > SSH do vašeho DSM a poté spusťte (jako sudo -i nebo root) `
> > > ```shell
> > > cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
> > > sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > A nyní můžete nainstalovat z GUI [9.2.0-11289](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289)
> > > A pokud chcete zabránit zobrazování upgradu v centru balíčků, stačí spustit tento řádek (jako sudo -i nebo root) v cli :
> > > ```shell
> > > cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
> > > sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (upravit: formátování)
> > 
> > 
> > Vyzkoušeno, ale nelze nainstalovat 9.2.0-11289
> 
> It works for me, properly installed version 9.2.0-11289 and license active.
> 
> DS224+ / DSM 7.2.2-72806 Update 2

Could you please provide more details on what process you followed? I am assuming you had first installed 9.2.1-11380 then ran the commands then uninstalled and then installed the old version? thanks in advance!
Edit- retried just to make sure, changing the command to replace version as I have 11380 instead of 11320 but I am still getting message stating:  "this package version is not compatible with your diskstation. Upload version 9.2.1-11380 or later instead

**Comment by helio58** [comment]
> > > > komukoli, kdo zde skončil po upgradu vašeho DSM na nejnovější verzi a nemůže již nainstalovat verzi 9.2.0-11289:
> > > > SSH do vašeho DSM a poté spusťte (jako sudo -i nebo root) `
> > > > ```shell
> > > > cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
> > > > sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > A nyní můžete nainstalovat z GUI [9.2.0-11289](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289)
> > > > A pokud chcete zabránit zobrazování upgradu v centru balíčků, stačí spustit tento řádek (jako sudo -i nebo root) v cli :
> > > > ```shell
> > > > cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
> > > > sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > (upravit: formátování)
> > > 
> > > 
> > > Vyzkoušeno, ale nelze nainstalovat 9.2.0-11289
> > 
> > 
> > It works for me, properly installed version 9.2.0-11289 and license active.
> > DS224+ / DSM 7.2.2-72806 Update 2
> 
> Could you please provide more details on what process you followed? I am assuming you had first installed 9.2.1-11380 then ran the commands then uninstalled and then installed the old version? thanks in advance! Edit- retried just to make sure, changing the command to replace version as I have 11380 instead of 11320 but I am still getting message stating: "this package version is not compatible with your diskstation. Upload version 9.2.1-11380 or later instead

I have the same problem unable to install 11320

**Comment by caspercze** [comment]
> > > > komukoli, kdo zde skončil po upgradu vašeho DSM na nejnovější verzi a nelze již nainstalovat verzi 9.2.0-11289: 
> > > > SSH do vašeho DSM a poté spusťte (jako sudo -i nebo root) `
> > > > ```shell
> > > > cp /etc.defaults/synopackageslimit.conf /etc.defaults/synopackageslimit.conf.bak
> > > > sed -i 's/SurveillanceStation="9.2.1-11320"/SurveillanceStation="9.2.0-11289"/g' /etc.defaults/synopackageslimit.conf
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > A nyní můžete nainstalovat z GUI [9.2.0-11289](https://github.com/ohyeah521/Surveillance-Station#surveillance-station-920-11289) 
> > > > A pokud chcete zachovat zobrazování upgradu v centru balíčků, stačí spustit tento řádek (jako sudo -i nebo root) v cli :
> > > > ```shell
> > > > cp /var/packages/SurveillanceStation/INFO /var/packages/SurveillanceStation/INFO.bak
> > > > sed -i 's/version="9.2.0-11289"/version="99.2.0-11289"/g' /var/packages/SurveillanceStation/INFO 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > (upravit: formátování)
> > > 
> > > 
> > > Vyzkoušeno, ale nelze nainstalovat 9.2.0-11289
> > 
> > 
> > Funguje mi to, správně nainstalovaná verze 9.2.0-11289 a licence aktivní.
> > DS224+ / DSM 7.2.2-72806 Aktualizace 2
> 
> Mohl byste prosím poskytnout více podrobností o tom, jaký proces jste sledovali? Předpokládám, že jste nejprve nainstalovali 9.2.1-11380, poté spustili příkazy, odinstalovali a nainstalovali starou verzi? předem děkuji! Upravit - pro jistotu zopakujte, změňte příkaz tak, aby nahradil verzi, protože mám 11380 místo 11320, ale stále se mi zobrazuje zpráva: "tato verze balíčku není kompatibilní s vaší diskovou stanicí. Místo toho nahrajte verzi 9.2.1-11380 nebo novější

Uninstalled version 9.2.1-11380 with settings and license, using ssh as root and used the first command. Then manually installed version 9.2.0 - 11289 (the system no longer reported that this version is not supported) and installed the licenses using the standard task manager.

Then used the second command via ssh as root so that it wouldn't report that a new version was available.
